manager:
  # Url de acesso a api do manager
  # Exemplo: https://192.168.1.200:8080
  url: ""
  # Usuário com permissões de escrita no fortimanager e com acesso a api
  usuario: ""
  senha: ""
  # Se o fortimanager usa ssl ou não
  ssl: True
  # Adom que será alterado
  adom: ""

youtube:
  # Chave de acesso a api do youtube do google
  api_key: ""
  # Se deseja verificar o certificado para a conexão
  ssl: True
